### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null 

### ISSUE THREAD

**Issue by jamiel-sharief** [joelgriffith/browserless#148]
I am running a docker development container and trying to access the docker browserless container (a second container). I have attached the container using the DockerCompose.yml.

I am getting an error elsewhere (if i change the ws endpoint to the server version, the script works fine).

DockerCompose.yml 
================
...
  browserless:
    image: browserless/chrome:latest
    ports:
        - "3000:3000"

Same as:
```linux
$ docker run --net=app_default --name=browserless  -p 3000:3000 browserless/chrome
```
NodeJS script
==========
```js
const puppeteer = require('puppeteer');

(async() => {

    try 
    {
        // Replace puppeteer.launch with puppeteer.connect
        const browser = await puppeteer.connect({
            browserWSEndpoint: 'ws://browserless:3000' 
        });

        const page = await browser.newPage();
        await page.goto('http://example.com');
        await page.screenshot({path: 'example.png'});
        await browser.close();
    }
    catch(error){
        console.log(error)
    }
  
})();
```

Error Output
===========
```
(node:15) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null
    at DOMWorld._setContext (/var/www/nodejs/node_modules/puppeteer/lib/DOMWorld.js:61:36)
    at FrameManager._onExecutionContextCreated (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:303:13)
    at CDPSession.FrameManager._client.on.event (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:52:70)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/var/www/nodejs/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/var/www/nodejs/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null
    at DOMWorld._setContext (/var/www/nodejs/node_modules/puppeteer/lib/DOMWorld.js:61:36)
    at FrameManager._onExecutionContextCreated (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:303:13)
    at CDPSession.FrameManager._client.on.event (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:52:70)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/var/www/nodejs/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/var/www/nodejs/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
````
Any ideas why the dockerimage is not working - I can connect to the public service no problems, and i see the debugger. I just cant seem to make requests to it.

I am using node v8.10.0

**Comment by joelgriffith** [comment]
I think this is a race condition we'll have fixed in `latest` here soon. I believe it stems from browserless setting a download dir on new page creation -- but is doing so too early.

I'll have you try the latest image here soon!

**Comment by joelgriffith** [comment]
Could you try to repro now on latest? Please pull first!

**Comment by jamiel-sharief** [comment]
Yes the script is working but it still displays errors, and as you correctly identified, it is when `await browser.newPage();` is called.

Note: Pulling the image did not work first time, i had to remove the existing image - maybe i did something wrong.
I have put the new output, just incase anything changed.
```
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null
    at DOMWorld._setContext (/var/www/nodejs/node_modules/puppeteer/lib/DOMWorld.js:61:36)
    at FrameManager._onExecutionContextCreated (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:303:13)
    at CDPSession.FrameManager._client.on.event (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:52:70)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/var/www/nodejs/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/var/www/nodejs/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
loading page
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null
    at DOMWorld._setContext (/var/www/nodejs/node_modules/puppeteer/lib/DOMWorld.js:61:36)
    at FrameManager._onExecutionContextCreated (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:303:13)
    at CDPSession.FrameManager._client.on.event (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:52:70)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/var/www/nodejs/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/var/www/nodejs/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by joelgriffith** [comment]
Just a heads up that this is a legit bug that _just_ got fixed in puppeteer: https://github.com/GoogleChrome/puppeteer/pull/4276
