### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null

### ISSUE THREAD

**Issue by jamielsharief** [joelgriffith/browserless#190]
When I run my Pupetter script through Browserless, I get this displayed on the screen. The script still works but 1) its annoying 2) it does not happen when i dont use browserless.

(node:172) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of null
    at DOMWorld._setContext (/var/www/nodejs/node_modules/puppeteer/lib/DOMWorld.js:61:36)
    at FrameManager._onExecutionContextCreated (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:303:13)
    at CDPSession.FrameManager._client.on.event (/var/www/nodejs/node_modules/puppeteer/lib/FrameManager.js:52:70)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/var/www/nodejs/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/var/www/nodejs/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/var/www/nodejs/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joelgriffith** [comment]
Yeah, this is an older bug in puppeteer that's now fixed after version 1.15.0. What version are you running?

**Comment by jamielsharief** [comment]
Sorry my bad. I have updated and now all is fine. thanks
