### ISSUE TITLE
What is the correct code for use with Puppeteer?

### ISSUE THREAD

**Issue by kingjerod** [joelgriffith/browserless#87]
Do we need to call `puppeteer.connect` everytime we want to load a page? And then after the page is loaded and we're done with it, call browser.close()? I'm currently trying that and getting this error from the Browserless container:

```
(node:22) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): Target closed.
    at Promise (/usr/src/app/node_modules/puppeteer/lib/Connection.js:73:56)
    at new Promise (<anonymous>)
    at Connection.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:72:12)
    at Connection.createSession (/usr/src/app/node_modules/puppeteer/lib/Connection.js:136:36)
    at Target [as _sessionFactory] (/usr/src/app/node_modules/puppeteer/lib/Browser.js:116:75)
    at Target.page (/usr/src/app/node_modules/puppeteer/lib/Target.js:42:32)
    at Target.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:145:23)
    at Promise.all.targets.filter.map.target (/usr/src/app/node_modules/puppeteer/lib/Browser.js:272:35)
    at Array.map (<anonymous>)
    at BrowserContext.pages (/usr/src/app/node_modules/puppeteer/lib/Browser.js:272:14)
```

I've tried instead to connect only once, re-use that browser session, and only open/close pages, leaving the browser connected. I've read through the docs and don't see a full example of this anywhere.

**Comment by joelgriffith** [comment]
One thing to rule-out: there is a global session timer (configurable of course). You’ll want to make sure to turn it off if your code is handling all the browser parallelism and closing.

Let me know if this helps: https://docs.browserless.io/docs/docker.html#connection-timeout. Setting to -1 turns off this timer

**Comment by joelgriffith** [comment]
Closing this due to inactivity, please feel free to chime back in or re-open if the issue persists

**Comment by heruputra** [comment]
Hi,

I just trying to turns off the timer using this command

`docker run -e "CONNECTION_TIMEOUT=-1" -p 3000:3000 browserless/chrome`

but puppeteer even can't open any sites.

**Comment by joelgriffith** [comment]
@heruputra if you're using the debugger this is a now-fixed bug (the debugger wasn't respecting that option)
